name: Databricks Serverless CI

on:
    push:
        branches: [main]

jobs:
    deploy-and-run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Databricks CLI (new)
              run: |
                  curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

            - name: Configure Databricks auth
              run: |
                  echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}" >> $GITHUB_ENV
                  echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}" >> $GITHUB_ENV

            - name: Validate bundle
              run: databricks bundle validate

            - name: Deploy bundle
              run: databricks bundle deploy -t dev

            - name: Run job
              run: databricks bundle run hello_world_job -t dev
